name: Pull Data to Server




on:

  push:

    branches:

      - main




jobs:

  backend:

    runs-on: mern  # Custom runner, ensure it supports node setup actions




    steps:

      - name: Set up SSH key for GitHub Actions


        run: |
          if [ ! -d "$HOME/.ssh" ]; then mkdir -p ~/.ssh; fi

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
         


      - name: Pull and Deploy Backend

        working-directory: /var/www/MERN---Docker_compose/mern/backend
        run: |

          echo "Pulling latest code for backend"

          

            git pull origin main && 
            
            npm install &&  #
            npm run build && 
            npm start

      - name: Pull and Deploy frontend

        working-directory: /var/www/MERN---Docker_compose/mern/frontend
        run: |

          echo "Pulling latest code for frontend"

          

            git pull origin main && 
            
            npm -f install &&  #
            npm run build && 
            npm start

      

          

